# Generated by Django 4.2.5 on 2023-10-23 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Name', models.CharField(choices=[('Mr', 'Marketing'), ('Hr', 'HR'), ('AS', 'Associate Software Engineer')], max_length=10)),
                ('Job_Detail', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prof_Name', models.CharField(choices=[('Dr', 'Doctor'), ('P', 'Pilot'), ('A', 'Artist'), ('E', 'Engineer')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_Name', models.CharField(choices=[('M', 'MB_IT'), ('N', 'NEO-PI-R'), ('B', 'BFI')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserType', models.CharField(choices=[('A', 'Admin'), ('E', 'Employer'), ('S', 'Student')], max_length=10)),
                ('User_Name', models.CharField(max_length=20)),
                ('User_Email', models.CharField(max_length=20)),
                ('User_Age', models.IntegerField()),
                ('User_Password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Traits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Traits_Name', models.CharField(choices=[('C', 'Creative'), ('A', 'Adaptive'), ('B', 'Balanced'), ('D', 'Disciplined')], max_length=10)),
                ('Prof_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PccModels.profession')),
                ('Test_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PccModels.test')),
                ('User_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PccModels.user')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='User_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PccModels.user'),
        ),
        migrations.AddField(
            model_name='profession',
            name='Test_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PccModels.test'),
        ),
        migrations.AddField(
            model_name='profession',
            name='User_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PccModels.user'),
        ),
        migrations.CreateModel(
            name='MatchingCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PccModels.jobpost')),
                ('User_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PccModels.traits')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeedBack', models.TextField(blank=True)),
                ('User_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PccModels.user')),
            ],
        ),
    ]
